### ISSUE TITLE
실례지만, 제가 당신에게 연락해도 될까요?나는 이 논문을 실현하고 싶다. 너와 교류하고 싶다

### ISSUE THREAD

**Issue by R1ckLou** [suker80/AEGN#1]
Thanks

**Comment by suker80** [comment]
sorry for your late reply.  What are you curious about?

**Comment by R1ckLou** [comment]
I'm a rookie,Have you implemented this model, please?

**Comment by suker80** [comment]
Yes. i tested this model ,generated images looks like pretty well

**Comment by R1ckLou** [comment]
Can you give me the code for this project as well as the dataset? I have no way to reproduce this thesis. I am very sorry to bother you.

**Comment by suker80** [comment]
But i didn't compare the exact indicators.

**Comment by suker80** [comment]
i implemented this model three years ago. I lost my dataset and there's no way to get it again.

**Comment by suker80** [comment]
I extracted all the letters for each font and used a self-made dataset.

**Comment by R1ckLou** [comment]
I just wanted to reproduce the paper and thank you very much for your reply. Since I don't have the dataset anymore, I'll figure it out myself. Thank you. I'm only in my first year of graduate school, so I'm a bit weak

**Comment by suker80** [comment]
I was also a rookie, and the model implemented may be slightly different. I wish you all the luck!
